# Generated by Django 5.2.16 on 2026-07-24 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_app', '0004_alter_telegramaccount_options_and_more'),
        ('contacts', '0002_alter_contact_email_alter_contact_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='telegram_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='channels_app.telegramaccount', verbose_name='Telegram-бот'),
        ),
    ]
