# Generated by Django 5.2.16 on 2026-07-20 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_user_phone_alter_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(blank=True, help_text='Фиксируется на момент события — не теряется при удалении аккаунта', max_length=150, verbose_name='Логин')),
                ('action', models.CharField(choices=[('created', 'Создано'), ('updated', 'Изменено'), ('deleted', 'Удалено'), ('moved', 'Перемещено'), ('login_success', 'Вход выполнен'), ('login_failed', 'Неудачная попытка входа')], max_length=20, verbose_name='Действие')),
                ('model_name', models.CharField(blank=True, max_length=50, verbose_name='Объект')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Кто')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Событие журнала',
                'verbose_name_plural': 'Журнал событий',
                'ordering': ['-created_at'],
            },
        ),
    ]
