# Generated by Django 5.2.16 on 2026-07-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_at'], 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('vk', 'VK'), ('phone', 'Телефон'), ('email', 'Email'), ('manual', 'Вручную')], default='manual', max_length=20, verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='direction',
            field=models.CharField(blank=True, choices=[('in', 'Входящее'), ('out', 'Исходящее')], max_length=10, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('call', 'Звонок'), ('message', 'Сообщение'), ('email', 'Email'), ('note', 'Заметка'), ('system', 'Системное событие')], max_length=20, verbose_name='Тип'),
        ),
    ]
