# Generated by Django 5.2.16 on 2026-07-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_app', '0002_alter_activity_options_alter_activity_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('manual', 'Вручную')], default='manual', max_length=20, verbose_name='Канал'),
        ),
    ]
