# Generated by Django 5.2.16 on 2026-07-24 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_phone_alter_user_role'),
        ('channels_app', '0003_alter_activity_channel'),
        ('contacts', '0002_alter_contact_email_alter_contact_full_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramaccount',
            options={'verbose_name': 'Telegram-бот', 'verbose_name_plural': 'Telegram-боты'},
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='collect_lead',
            field=models.BooleanField(default=False, help_text='Бот задаст новому клиенту вопросы ниже и сохранит ответы в контакт.', verbose_name='Собирать анкету лида'),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='help_text_message',
            field=models.TextField(blank=True, verbose_name='Ответ на /help'),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='lead_done_text',
            field=models.TextField(blank=True, verbose_name='Сообщение после анкеты'),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='operator_text',
            field=models.TextField(blank=True, verbose_name='Ответ на /operator'),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='title',
            field=models.CharField(blank=True, help_text='Внутреннее имя бота, например «Основной» или «Поддержка».', max_length=100, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='welcome_text',
            field=models.TextField(blank=True, help_text='Оставьте пустым — будет использован текст по умолчанию.', verbose_name='Приветствие (/start)'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='bot_token',
            field=models.CharField(max_length=200, verbose_name='Токен бота'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Бот активен'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_accounts', to='accounts.organization'),
        ),
        migrations.CreateModel(
            name='LeadQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('text', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('target', models.CharField(choices=[('full_name', 'Имя клиента'), ('phone', 'Телефон'), ('email', 'Email'), ('note', 'В заметку контакта')], default='note', max_length=20, verbose_name='Куда сохранить ответ')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='channels_app.telegramaccount')),
            ],
            options={
                'verbose_name': 'Вопрос анкеты',
                'verbose_name_plural': 'Вопросы анкеты',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LeadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_index', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_sessions', to='channels_app.telegramaccount')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_sessions', to='contacts.contact')),
            ],
            options={
                'unique_together': {('account', 'contact')},
            },
        ),
    ]
