# Generated by Django 5.2.16 on 2026-07-24 16:50

from django.db import migrations, models

TOKEN = "[не отправлено:"


def backfill_failed(apps, schema_editor):
    """Переносит старую пометку «[не отправлено: …]» из текста сообщения в
    отдельные поля статуса доставки и очищает текст."""
    Activity = apps.get_model('channels_app', 'Activity')
    for activity in Activity.objects.filter(text__contains=TOKEN):
        pos = activity.text.find(TOKEN)
        head = activity.text[:pos].rstrip()
        reason = activity.text[pos + len(TOKEN):].strip()
        if reason.endswith("]"):
            reason = reason[:-1].strip()
        activity.text = head
        activity.delivery_failed = True
        activity.delivery_error = reason[:500]
        activity.save(update_fields=["text", "delivery_failed", "delivery_error"])


class Migration(migrations.Migration):

    dependencies = [
        ('channels_app', '0004_alter_telegramaccount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='delivery_error',
            field=models.CharField(blank=True, max_length=500, verbose_name='Причина'),
        ),
        migrations.AddField(
            model_name='activity',
            name='delivery_failed',
            field=models.BooleanField(default=False, verbose_name='Не доставлено'),
        ),
        migrations.RunPython(backfill_failed, migrations.RunPython.noop),
    ]
