# Generated by Django 5.2.16 on 2026-07-17 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_role'),
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('trigger', models.CharField(choices=[('stage_changed', 'Сделка перешла на этап'), ('payment_received', 'Получена оплата'), ('no_activity', 'Нет активности по сделке N дней')], max_length=30)),
                ('no_activity_days', models.PositiveIntegerField(blank=True, help_text='Для триггера «Нет активности N дней»', null=True)),
                ('action', models.CharField(choices=[('create_task', 'Создать задачу'), ('move_to_stage', 'Переместить сделку на этап'), ('log_activity', 'Записать системное событие')], max_length=30)),
                ('task_type', models.CharField(blank=True, choices=[('call', 'Позвонить'), ('meeting', 'Встреча'), ('invoice', 'Выставить счёт'), ('follow_up', 'Напомнить о себе'), ('other', 'Другое')], help_text='Для действия «Создать задачу»', max_length=20)),
                ('task_title', models.CharField(blank=True, max_length=255)),
                ('task_due_in_hours', models.PositiveIntegerField(default=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_target_stage', models.ForeignKey(blank=True, help_text='Для действия «Переместить сделку на этап»', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='deals.stage')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='accounts.organization')),
                ('trigger_stage', models.ForeignKey(blank=True, help_text='Для триггера «Сделка перешла на этап»', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='deals.stage')),
            ],
        ),
    ]
