# Generated by Django 5.2.16 on 2026-07-20 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
        ('deals', '0003_alter_deal_amount_alter_deal_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationrule',
            name='action',
            field=models.CharField(choices=[('create_task', 'Создать задачу'), ('move_to_stage', 'Переместить сделку на этап'), ('log_activity', 'Записать системное событие')], max_length=30, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='action_target_stage',
            field=models.ForeignKey(blank=True, help_text='Для действия «Переместить сделку на этап»', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='deals.stage', verbose_name='Целевой этап'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='no_activity_days',
            field=models.PositiveIntegerField(blank=True, help_text='Для триггера «Нет активности N дней»', null=True, verbose_name='Дней без активности'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='task_due_in_hours',
            field=models.PositiveIntegerField(default=24, verbose_name='Срок задачи, часов'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='task_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Текст задачи'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='task_type',
            field=models.CharField(blank=True, choices=[('call', 'Позвонить'), ('meeting', 'Встреча'), ('invoice', 'Выставить счёт'), ('follow_up', 'Напомнить о себе'), ('other', 'Другое')], help_text='Для действия «Создать задачу»', max_length=20, verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='trigger',
            field=models.CharField(choices=[('stage_changed', 'Сделка перешла на этап'), ('payment_received', 'Получена оплата'), ('no_activity', 'Нет активности по сделке N дней')], max_length=30, verbose_name='Триггер'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='trigger_stage',
            field=models.ForeignKey(blank=True, help_text='Для триггера «Сделка перешла на этап»', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='deals.stage', verbose_name='Этап-триггер'),
        ),
    ]
